a.out: GetArray.o ShiftRight.o MaxIncreasingSequence.o Palindrome.o Calculator.o SecondLargest.o main.o 
	gcc GetArray.o ShiftRight.o MaxIncreasingSequence.o Palindrome.o Calculator.o SecondLargest.o main.o 
GetArray.o: GetArray.c GetArray.h
	gcc -c GetArray.c 
ShiftRight.o: ShiftRight.c ShiftRight.h
	gcc -c ShiftRight.c
MaxIncreasingSequence.o: MaxIncreasingSequence.c MaxIncreasingSequence.h
	gcc -c MaxIncreasingSequence.c
Palindrome.o: Palindrome.c Palindrome.h
	gcc -c Palindrome.c
Calculator.o: Calculator.c Calculator.h
	gcc -c Calculator.c
SecondLargest.o: SecondLargest.c SecondLargest.h
	gcc -c SecondLargest.c
main.o: main.c
	gcc -c main.c


